### PR TITLE
ST4 Overhaul 

### LINKED ISSUE #108: [Update] - Update to the latest version of simplejson
**What**
Upgrade to the latest version of simplejson

**Why**
Keep current with utilized libraries and performance increases

### LINKED ISSUE #109: Broken logic for empty regions and entire file
**What**
If a user has multiple selections and a single selection is `empty()` the entire file is evaluated. This is incorrect logic. Additionally, it will attempt to evaluate the entire file for each region that is selected and is empty.

So in a case such as the below, it will attempt to evaluate the file 2 times. Even though we have multiple selections. Additionally, this can lead to performance impact if the view (buffer) is rather large.

image

Suggested fix would be to separate the logic of entire file and region. 

https://github.com/dzhibas/SublimePrettyJson/blob/ea5264c08c4e274056f93c144ade7496d43fa7dd/PrettyJson.py#L188

### LINKED ISSUE #110: Duplicate keys are incorrectly shown as valid json
```
{
  "a" : "x",
  "a" : "y"
}
```

The above json is incorrect as `"a"` is repeated key, but is shown as valid.
Screenshot below:

Screen Shot 2020-04-09 at 12 18 53 PM

This is shown as a valid json.

However when I do a format and sort json, it changes this to
```
{
  "a": "y"
}
```

### PR DESCRIPTION
**Pull request by TheSecEng**
## Why
Update the plugin for ST4 support and utilize some more advance features of ST.

## What
A short list of changes done and/or planned
### Planned
- [x] Fix #109 - FIx `region.empty()`
- [x] Fix #108 - Update SimpleJson
- [x] Fix #110 - Added `json.JSONDecoder`
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/89
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/88
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/85
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/81
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/80
- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/79

- [x] Implement https://github.com/dzhibas/SublimePrettyJson/pull/77
- [x] Overall formatting updates
- [x] Update Sublime menu entries
- [x] Remove python2 support
- [x] Update error highlighting to utilize phantoms to provide detailed information
- [x] Live JQ Filtering

### Per Guidance Below [jrappen](https://github.com/jrappen)
- [ ] Update Readme
- [x] libs → lib
- [x] Type Hinting
- [x] .gitattributes
- [x] .python-version
- [x] JSON 2 XML Rename
- [x] Side-by-side Settings
- [x] Double Quote → Single Quote

### CODE REVIEW

**Comment by TheSecEng** [comment]
Preview of what I am thinking about for error messages

image

**Comment by TheSecEng** [comment]
And multi selection support

image

**Comment by jrappen** [comment]
Since you asked for feedback:

- use Py3.8 since there are no dependencies
  - use f-strings
  - add type hints
  - Thomas made a list for Py3.3 vs Py3.8 at https://discordapp.com/channels/280102180189634562/280157067396775936/644243028353220675
  - remove Py2 vs Py3 code and ST2 compatibility, only something like 2% of users were on ST2 the last time we got numbers from Will and that was over a year ago.
- use GitHub actions instead of Travis
- remove the `.no-sublime-package` file now that you removed the c file as there are no binary files left
- maybe add a `.gitattributes` file to remove tests from shipped package for smaller zip files shipped to users, this is subjective though
- general Sublime stuff:
  - `Default.sublime-commands`:
    - open settings side-by-side
    - the `JSON 2 XML` caption should probably be `json2xml`
  - `Main.sublime-menu`:
    - open settings side-by-side
  - `README.md`:
    - maybe add a TOC
    - use header3 for configurations and move default values with description into a list?
- general Python stuff
  - use single quotes
  - use `lib` not `libs`

---

Also you might want to update the package requirements on the package_control_channel repo once you're done, but you knew that, right.

**Comment by TheSecEng** [comment]
@jrappen Thank you very much for the feedback!

**Comment by TheSecEng** [comment]
@dzhibas Thoughts on the idea of this overhaul? Would this be something you support?

**Comment by jrappen** [comment]
@TheSecEng When extending menus of other packages (here PackageControl), only reference items by `id`. Do not add `caption` or `mnemonic`.

**Comment by dzhibas** [comment]
> @dzhibas Thoughts on the idea of this overhaul? Would this be something you support?

Hey @TheSecEng pretty awesome work! Had no idea ST4 is ready. Do you want to take over this package ownership? Not sure if at this moment i have time to support this

**Comment by TheSecEng** [comment]
I totally understand ! ST is close to being fully available, I’ll keep tags/branches so that there will still be a version available that is compatible with ST3 as well. 

I’d be happy to take over this package if you don’t have time.

**Comment by TheSecEng** [comment]
Live JQ Filtering

**Pull request merged**
