### PR TITLE
Add bits of None- and type-safety to the plugin code

### LINKED ISSUE #180: AttributeError: 'PrettyJsonLintListener' object has no attribute 'view'
When creating a new file and saving it, Pretty JSON fails with the following traceback in console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 934, in on_post_save
    run_view_callbacks('on_post_save', view_id)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/home/ratijas/.config/sublime-text/Installed Packages/Pretty JSON.sublime-package/PrettyJsonListeners.py", line 16, in on_post_save
    self.clear_phantoms()
  File "/home/ratijas/.config/sublime-text/Installed Packages/Pretty JSON.sublime-package/PrettyJson.py", line 194, in clear_phantoms
    self.phantom_set = sublime.PhantomSet(self.view, "json_errors")
AttributeError: 'PrettyJsonLintListener' object has no attribute 'view'
```

### PR DESCRIPTION
**Pull request by ratijas**
Fixed #180

### CODE REVIEW

**Comment by mortalis13** [comment]
Thanks for posting it. I also found this on saving json files.

But I think just assigning `self.view = view` in both listeners would be a quick valid solution, in `PrettyJsonListeners.py`.

As yours gives me another error on save (which I don't know where it comes from...):
```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1691, in run_
    edit = self.view.begin_edit(edit_token, self.name())
AttributeError: 'NoneType' object has no attribute 'begin_edit'
```

The view is intended to be provided by the base plugin class instances, so `PrettyJsonBaseCommand` is a mixin which has access to the view.
But `PrettyJsonLintListener` doesn't have view attribute `self.view`, so it cannot pass it to its mixin instance of `PrettyJsonBaseCommand`. That's why `def on_post_save(self, view):` has view as argument.

So I'd say it's incorrectly inherits from `PrettyJsonBaseCommand` and it would need to be redesigned,
maybe using a constructor argument as in your code, but creating an instance from the listener method,
but the commands should also do it, instead of inheriting the mixin.

**Comment by mortalis13** [comment]
Anyway, this seems an abandoned project, so I'll use my fork for me, and will create a clone package on package control some day, if someone else doesn't do it until then...

**Comment by ratijas** [comment]
The fact I already forgot about my PR and the fact that it's still not merged is a certified GitHub moment™

Projects like this should be moved under bigger organizations / umbrellas with a pool of maintainers and on-boarding/off-boarding processes.

**Comment by deathaxe** [comment]
This PR is obsolete.

**Comment by ratijas** [comment]
cool, thanks!

**Pull request closed without merging**
